_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 41
                - 51
                - 55
            "2":
                - 1
                - 41
                - 51
                - 55
            "3":
                - 13
                - 19
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
affine:
    value: false
arch_learning_rate:
    value: 0.0003
arch_weight_decay:
    value: 0.001
batch_size:
    value: 64
channel:
    value: 32
criterion:
    value: Softmax
cutout:
    value: 0
epochs:
    value: 100
learning_rate_min:
    value: 0.001
lr:
    value: 0.025
max_nodes:
    value: 2
momentum:
    value: 0.9
nesterov:
    value: true
optim:
    value: SGD
reg_scale:
    value: 0.001
reg_type:
    value: l2
seed:
    value: 9001
track_running_stats:
    value: true
train_portion:
    value: 0.5
use_data_parallel:
    value: false
weight_decay:
    value: 0.0005
