#!/bin/bash
#SBATCH -p mldlc_gpu-rtx2080
#SBATCH --gres=gpu:8
#SBATCH -t 6-00:00:00 # time (D-HH:MM)
#SBATCH -c 16 # number of cores
#SBATCH -o logs/%j.%x.%N.out # STDOUT  (the folder log has to be created prior to running or this won't work)
#SBATCH -e logs/%j.%x.%N.err # STDERR  (the folder log has to be created prior to running or this won't work)
#SBATCH -J darts_af_budgets # sets the job name. If not specified, the file name will be used as job name
#SBATCH --mail-type=END,FAIL # (recive mails about end and timeouts/crashes of your job)
#python -m torch.distributed.launch --nproc_per_node=8  --master_port=1723 --use_env search_spaces/AutoFormer/supernet_train_inherit.py --data-set CIFAR10 --gp --change_qkv --relative_position --mode super --dist-eval --cfg search_spaces/AutoFormer/experiments/supernet/supernet-T.yaml  --patch_size 16  --epochs 200 --warmup-epochs 20 --output cifar10_finetune_gdas_0_8_75/ --batch-size 64 --amp --model_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_gdas_1000_0_8_224_we2/checkpoint_563.pth  --df_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_gdas_1000_0_8_224_we2/arch_trajectory.pkl  --arch_epoch 563 --lr 1e-5 --warmup-lr 1e-5 --min-lr 1e-6 --seed 9001
#python -m torch.distributed.launch --nproc_per_node=8  --master_port=1723 --use_env search_spaces/AutoFormer/supernet_train_inherit.py --data-set CIFAR10 --gp --change_qkv --relative_position --mode super --dist-eval --cfg search_spaces/AutoFormer/experiments/supernet/supernet-T.yaml  --patch_size 16  --epochs 100 --warmup-epochs 20 --output cifar10_finetune_gdas_0_8_100/ --batch-size 64 --amp --model_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_gdas_1000_0_8_224_we2/checkpoint_750.pth  --df_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_gdas_1000_0_8_224_we2/arch_trajectory.pkl  --arch_epoch 750 --lr 1e-5 --warmup-lr 1e-5 --min-lr 1e-6 --seed 9001
#python -m torch.distributed.launch --nproc_per_node=8  --master_port=1723 --use_env search_spaces/AutoFormer/supernet_train_inherit.py --data-set CIFAR10 --gp --change_qkv --relative_position --mode super --dist-eval --cfg search_spaces/AutoFormer/experiments/supernet/supernet-T.yaml  --patch_size 16  --epochs 300 --warmup-epochs 20 --output cifar10_finetune_gdas_0_8_50/ --batch-size 64 --amp --model_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_gdas_1000_0_8_224_we2/checkpoint_375.pth  --df_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_gdas_1000_0_8_224_we2/arch_trajectory.pkl  --arch_epoch 375 --lr 1e-5 --warmup-lr 1e-4 --min-lr 1e-6  --seed 9001
#python -m torch.distributed.launch --nproc_per_node=8  --master_port=1723 --use_env search_spaces/AutoFormer/supernet_train_inherit.py --data-set CIFAR10 --gp --change_qkv --relative_position --mode super --dist-eval --cfg search_spaces/AutoFormer/experiments/supernet/supernet-T.yaml  --patch_size 16  --epochs 400 --warmup-epochs 20 --output cifar10_finetune_gdas_0_8_25/ --batch-size 64 --amp --model_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_gdas_1000_0_8_224_we2/checkpoint_188.pth  --df_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_gdas_1000_0_8_224_we2/arch_trajectory.pkl  --arch_epoch 188 --lr 1e-5 --warmup-lr 1e-4 --min-lr 1e-6  --seed 9001
#######################
#python -m torch.distributed.launch --nproc_per_node=8  --master_port=1723 --use_env search_spaces/AutoFormer/supernet_train_inherit.py --data-set CIFAR10 --gp --change_qkv --relative_position --mode super --dist-eval --cfg search_spaces/AutoFormer/experiments/supernet/supernet-T.yaml  --patch_size 16  --epochs 200 --warmup-epochs 20 --output cifar10_finetune_drnas_0_8_75/ --batch-size 64 --amp --model_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_drnas_1000_0_8_224_we2/checkpoint_563.pth  --df_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_drnas_1000_0_8_224_we2/arch_trajectory.pkl  --arch_epoch 563 --lr 1e-5 --warmup-lr 1e-5 --min-lr 1e-6
#python -m torch.distributed.launch --nproc_per_node=8  --master_port=1723 --use_env search_spaces/AutoFormer/supernet_train_inherit.py --data-set CIFAR10 --gp --change_qkv --relative_position --mode super --dist-eval --cfg search_spaces/AutoFormer/experiments/supernet/supernet-T.yaml  --patch_size 16  --epochs 100 --warmup-epochs 20 --output cifar10_finetune_drnas_0_8_100/ --batch-size 64 --amp --model_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_drnas_1000_0_8_224_we2/checkpoint_750.pth  --df_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_drnas_1000_0_8_224_we2/arch_trajectory.pkl  --arch_epoch 750 --lr 1e-5 --warmup-lr 1e-5 --min-lr 1e-6
#python -m torch.distributed.launch --nproc_per_node=8  --master_port=1723 --use_env search_spaces/AutoFormer/supernet_train_inherit.py --data-set CIFAR10 --gp --change_qkv --relative_position --mode super --dist-eval --cfg search_spaces/AutoFormer/experiments/supernet/supernet-T.yaml  --patch_size 16  --epochs 300 --warmup-epochs 20 --output cifar10_finetune_drnas_0_8_50/ --batch-size 64 --amp --model_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_drnas_1000_0_8_224_we2/checkpoint_375.pth  --df_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_drnas_1000_0_8_224_we2/arch_trajectory.pkl  --arch_epoch 375 --lr 1e-5 --warmup-lr 1e-4 --min-lr 1e-6
#python -m torch.distributed.launch --nproc_per_node=8  --master_port=1723 --use_env search_spaces/AutoFormer/supernet_train_inherit.py --data-set CIFAR10 --gp --change_qkv --relative_position --mode super --dist-eval --cfg search_spaces/AutoFormer/experiments/supernet/supernet-T.yaml  --patch_size 16  --epochs 400 --warmup-epochs 20 --output cifar10_finetune_drnas_0_8_25/ --batch-size 64 --amp --model_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_drnas_1000_0_8_224_we2/checkpoint_188.pth  --df_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_drnas_1000_0_8_224_we2/arch_trajectory.pkl  --arch_epoch 188 --lr 1e-5 --warmup-lr 1e-4 --min-lr 1e-6
#######################
python -m torch.distributed.launch --nproc_per_node=8  --master_port=1723 --use_env search_spaces/AutoFormer/supernet_train_inherit.py --data-set CIFAR10 --gp --change_qkv --relative_position --mode super --dist-eval --cfg search_spaces/AutoFormer/experiments/supernet/supernet-T.yaml  --patch_size 16  --epochs 300 --warmup-epochs 20 --output cifar10_finetune_darts_0_8_75/ --batch-size 64 --amp --model_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_darts_1000_0_8_224_we2/checkpoint_563.pth  --df_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_darts_1000_0_8_224_we2/arch_trajectory.pkl  --arch_epoch 563 --lr 1e-5 --warmup-lr 1e-5 --min-lr 1e-6
python -m torch.distributed.launch --nproc_per_node=8  --master_port=1723 --use_env search_spaces/AutoFormer/supernet_train_inherit.py --data-set CIFAR10 --gp --change_qkv --relative_position --mode super --dist-eval --cfg search_spaces/AutoFormer/experiments/supernet/supernet-T.yaml  --patch_size 16  --epochs 200 --warmup-epochs 20 --output cifar10_finetune_darts_0_8_100/ --batch-size 64 --amp --model_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_darts_1000_0_8_224_we2/checkpoint_750.pth  --df_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_darts_1000_0_8_224_we2/arch_trajectory.pkl  --arch_epoch 750 --lr 1e-5 --warmup-lr 1e-5 --min-lr 1e-6
python -m torch.distributed.launch --nproc_per_node=8  --master_port=1723 --use_env search_spaces/AutoFormer/supernet_train_inherit.py --data-set CIFAR10 --gp --change_qkv --relative_position --mode super --dist-eval --cfg search_spaces/AutoFormer/experiments/supernet/supernet-T.yaml  --patch_size 16  --epochs 400 --warmup-epochs 20 --output cifar10_finetune_darts_0_8_50/ --batch-size 64 --amp --model_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_darts_1000_0_8_224_we2/checkpoint_375.pth  --df_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_darts_1000_0_8_224_we2/arch_trajectory.pkl  --arch_epoch 375 --lr 1e-5 --warmup-lr 1e-4 --min-lr 1e-6
python -m torch.distributed.launch --nproc_per_node=8  --master_port=1723 --use_env search_spaces/AutoFormer/supernet_train_inherit.py --data-set CIFAR10 --gp --change_qkv --relative_position --mode super --dist-eval --cfg search_spaces/AutoFormer/experiments/supernet/supernet-T.yaml  --patch_size 16  --epochs 500 --warmup-epochs 20 --output cifar10_finetune_darts_0_8_25/ --batch-size 64 --amp --model_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_darts_1000_0_8_224_we2/checkpoint_188.pth  --df_path /work/dlclarge2/sukthank-tanglenas/TangleNAS-dev/output_cifar10_darts_1000_0_8_224_we2/arch_trajectory.pkl  --arch_epoch 188 --lr 1e-5 --warmup-lr 1e-4 --min-lr 1e-6
